name: Insane
main: no.insane.insane.Insane
version: 0.1
website: 'http://www.insane.no'
authors: ['Xstasy']
commands:
    bruker:
        description: Sender info om egen bruker
        usage: |
               /<command>